### ISSUE TITLE
HTML entities in HTML5 kill parsing

### ISSUE THREAD

**Issue by kaefer3000** [levkhomich/semargl#37]
Hi,

when parsing `http://schema.org/Person`, the parser only emits a handful of triples because of problems with HTML entities such as `&nbsp;` or `&ouml;` other than the default XML escapes `&lt;` and `&amp;`. This is because there is no DTD for HTML5 as it was there for HTML4 which would define the escapes. The doctype of HTML5 is a mere `<!DOCTYPE html>` mentioning no DTD. Yet, the escapes are allowed and around and thus it would be great if semargl would support that.

Having fixed that, the aforementioned page does also not parse entirely because the authors of the page failed to escape a `&`, but that's a different issue (yet it would be cool if it would not kill semargl).

Cheers,

Tobias

**Comment by levkhomich** [comment]
Hi,

Semargl avoids additional dependencies, that is why internally it uses standard XML parser. SAXParseException was thrown because source contained invalid XML markup. That's normal for HTML pages and can be avoided if you will use error-prone HTML parser (which produces well-formed XML) such as [HTMLCleaner](http://htmlcleaner.sourceforge.net/), [TagSoup](http://ccil.org/~cowan/XML/tagsoup/), [nu.validator](http://about.validator.nu/) and so on.

After creating one of theirs `XMLReader`s you can make Semargl to use it using
```java
sp.setProperty(StreamProcessor.XML_READER_PROPERTY, yourXmlReader);
```

Have you tried using [project's demo](http://semarglproject.org/demo-rdfa.html)? Is it able to extract triples? It uses HTMLCleaner underneath.

**Comment by levkhomich** [comment]
I've updated examples to show this approach, see [RdfaProcessorEndpoint.java](https://github.com/levkhomich/semargl/blob/master/examples/src/main/java/org/semarglproject/example/RdfaProcessorEndpoint.java).

**Comment by kaefer3000** [comment]
Hi,

pretty cool, thanks! The demo manages to extract the data. I had used semargl from within Any23, which seems not to have a cleaner enabled (maybe they should).

Cheers!

**Comment by levkhomich** [comment]
It seems like Any23 uses TagSoup internally only on specific processing stages, but not for RDFa triples extraction. Couldn't find any easy way to change extractor properties using Any23 API (it can be done using Sesame or Semargl API layers which are used underneath), but you can always fix input before passing it to Any23. For example, you can do following (didn't check if it actually works, just sketching):

```java
// create TagSoup reader
XMLReader reader = SAXParserImpl.newInstance(null).getXMLReader();
streamProcessor.setProperty(StreamProcessor.XML_READER_PROPERTY, reader);

// use it's writer to serialize SAX to string
ByteArrayOutputStream baos = new ByteArrayOutputStream();
XMLWriter writer = new XMLWriter(new OutputStreamWriter(baos));
reader.setContentHandler(writer);

// prepare input for TagSoup
URL url = new URL("http://example.com");
Reader urlReader = new InputStreamReader(url.openStream());

// actually, read url and serialize repaired markup to string
reader.parse(new InputSource(urlReader));

// use results as Any23 input
String input = new String(baos.toByteArray(), Charset.forName("UTF-8"));
DocumentSource source = new StringDocumentSource(input, url.toString())
runner.extract(source, handler);
```

**Comment by kaefer3000** [comment]
ok, many thanks, I think this solves my problems :)
